services:
  web:
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./server:/var/www/html
      - ./apache2:/etc/apache2
  db:
    image: mysql:latest
    ports:
        - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=coffeeshop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    