services:
  web:
    image: php:8.0-apache
    ports:
      - "8082:80"
    volumes:
      - ./server:/var/www/html
      - ./apache2:/etc/apache2
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volunes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    